const data = {
  products: [
    {
      _id: '1',
      name: 'Lambo',
      category: 'Sport',
      image: '/images/lambo.jpg',
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock:6,
      description: 'Sports car',
    },
    {
      _id: '2',
      name: 'Fusca',
      category: 'Collection',
      image: '/images/fusca.jpeg',
      price: 40,
      brand: 'Fusca',
      rating: 4.0,
      numReviews: 10,
      countInStock:3,
      description: 'Collection',
    },
    {
      _id: '3',
      name: 'Tesla',
      category: 'Sport',
      image: '/images/tesla.jpeg',
      price: 220,
      brand: 'Tesla',
      rating: 4.8,
      numReviews: 17,
      countInStock:9,
      description: 'Sports car',
    },
    {
      _id: '4',
      name: 'Aston Martin ',
      category: 'Pants',
      image: '/images/astonmartin.jpg',
      price: 78,
      brand: 'Aston Martin',
      rating: 4.5,
      numReviews: 14,
      countInStock:2,
      description: 'Sports',
    },
    {
      _id: '5',
      name: 'Lambo',
      category: 'Pants',
      image: '/images/lambo.jpg',
      price: 65,
      brand: 'Lambo',
      rating: 4.5,
      numReviews: 10,
      countInStock:0,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Lambo',
      category: 'Pants',
      image: '/images/lambo.jpg',
      price: 139,
      brand: 'Lambo',
      rating: 4.5,
      numReviews: 15,
      countInStock:0,
      description: 'high quality product',
    },
  ],
};
export default data;